# Generated by Django 6.0.1 on 2026-05-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TellerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teller_name', models.CharField(max_length=100)),
                ('cash_drawer_opening_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cash_drawer_closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('session_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
